// Generated by CoffeeScript 1.9.2
var decimalAdjust;

decimalAdjust = function(type, value, exp) {
  if (typeof exp === 'undefined' || +exp === 0) {
    return Math[type](value);
  }
  value = +value;
  exp = +exp;
  if (isNaN(value) || !(typeof exp === 'number' && exp % 1 === 0)) {
    return NaN;
  }
  value = value.toString().split('e');
  value = Math[type](+(value[0] + 'e' + (value[1] ? +value[1] - exp : -exp)));
  value = value.toString().split('e');
  return +(value[0] + 'e' + (value[1] ? +value[1] + exp : exp));
};

module.exports = {
  round10: function(value, exp) {
    return decimalAdjust('round', value, exp);
  },
  floor10: function(value, exp) {
    return decimalAdjust('floor', value, exp);
  },
  ceil10: function(value, exp) {
    return decimalAdjust('ceil', value, exp);
  }
};
